name = "playjonny-casino-com-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "public"

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=playjonny-casino.com.es"
HMAC_KEY = "a74d4d85a1e43d0fd859876d23ef818d3f6dc6b39619186cdd86f4519cef1466"
COOKIE_NAME = "jo6"
PLAY_PATH = "try"
BUTTON_ID = "p511959534535ec8e7d312934b26c70aa"
GATE_SALT = "70942eb866519271"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "ckmb"
CTA_SELECTOR = ".play-button"
